# Generated by Django 5.1.3 on 2025-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viagem',
            name='caminho',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='metodo',
            field=models.CharField(choices=[('custo_uniforme', 'Custo Uniforme'), ('profundidade', 'Aprofundamento Progressivo'), ('sofrega', 'Procura Sofrega'), ('a_estrela', 'A*')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viagem',
            name='nos_expandidos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
